version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - type: bind
        source: ./crime_data.csv
        target: /app/crime_data.csv
    environment:
      - FLASK_ENV=development
